<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use Illuminate\Support\Facades\Storage;
use Faker\Factory as Faker;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();

        // Define categories
        $categories = [
            ['name' => 'Sarung', 'slug' => 'kategori-sarung'],
            ['name' => 'Fashion', 'slug' => 'kategori-fashion'],
            ['name' => 'Aksesoris', 'slug' => 'kategori-aksesoris'],
        ];

        // Create categories with random images generated by Faker
        foreach ($categories as $categoryData) {
            $category = Category::create([
                'name' => $categoryData['name'],
                'slug' => $categoryData['slug'],
            ]);

            // Generate a random image using Faker and save it to storage
            $imagePath = 'public/categories/' . $faker->image('public/storage/categories', 640, 480, null, false);
            $imageFile = basename($imagePath);

            // Update the category with the generated image path
            $category->update(['image' => "categories/{$imageFile}"]);
        }
    }
}
