[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
  "php artisan migrate --force",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "rm -rf public/storage",
  "php artisan storage:link"
]

[variables]
APP_ENV = "production"
APP_DEBUG = "false"