[phases.setup]
cmds = [
      "composer install --no-dev --optimize-autoloader",
        "php artisan key:generate",
          "php artisan migrate --force",
            "php artisan config:cache",
              "php artisan route:cache",
                "php artisan view:cache",
                  "rm -rf public/storage",  # Perintah untuk menghapus folder public/storage
                    "php artisan storage:link"  # Perintah untuk membuat symlink kembali
]

[phases.build]
cmds = [
      "npm install",
        "npm run production"
]

[phases.start]
cmds = [
      "php artisan serve --host=0.0.0.0 --port=$PORT"
]

[variables]
APP_ENV = "production"
APP_DEBUG = "false"