[phases.setup]
commands = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan key:generate",
  "php artisan migrate --force",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "rm -R public/storage",  # Perintah untuk menghapus folder public/storage
  "php artisan storage:link"  # Perintah untuk membuat symlink kembali
]

[phases.build]
commands = [
  "npm install",
  "npm run build"
]

[variables]
APP_ENV = "production"
APP_DEBUG = "false"